flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/jabaraster/jabara-util
    commit: f974a3be2544b1e54c8751476ed7d997b82b96c6
extra-deps:
- http-querystring-1.0
resolver: lts-6.3
